#!/usr/bin/env ruby

# Regular expression to match a string with a character repeated at least 3 times
regex = /^(.)\1{2,}$/

# Get the input from ARGV
input = ARGV[0]

# Match the input with the regular expression
if regex.match(input)
  puts "Match"
else
  puts "No match"
end
