#!/bin/bash

# Set IFS to ":" to split the fields in /etc/passwd
IFS=':'

# Read /etc/passwd line by line
while read -r username password user_id group_id user_info home_directory shell; do
    # Display the formatted output
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
