#!/bin/bash

# Use awk to extract IP and HTTP status code, group and count occurrences
awk '{print $1, $9}' apache-access.log | \
    sort | \
    uniq -c | \
    sort -nr | \
    awk '{print $1, $2, $3}'
