#!/usr/bin/env bash
# This script checks the properties of the file named 'school'.

if [[ -e school ]]; then  # Check if the file exists
    echo "school file exists"
    
    if [[ -s school ]]; then  # Check if the file is not empty
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [[ -f school ]]; then  # Check if it is a regular file
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
