#!/usr/bin/env bash

# This script changes the IP addresses that localhost and facebook.com resolve to

# Update localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Update facebook.com to resolve to 8.8.8.8
sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
